name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: git clone --depth 1 https://git.private.coffee/PrivateCoffee/wikimore.git "$PWD"
    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: actions/cache@v4
      id: cache
      with:
        path: cache-mount
        key: cache-mount-${{ hashFiles('Dockerfile') }}

    - uses: reproducible-containers/buildkit-cache-dance@v3
      with:
        builder: ${{ steps.setup-buildx.outputs.name }}
        cache-dir: cache-mount
        dockerfile: Dockerfile
        skip-extraction: ${{ steps.cache.outputs.cache-hit }}
    - uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: "tlan16/wikimore"
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64,linux/arm64,linux/arm/v7
    - uses: peter-evans/dockerhub-description@v5
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: tlan16/wikimore
